use super::{SpriteDefinition, SpriteWindowDefinition, WindowType};

pub fn balance_sprites() -> Vec<SpriteDefinition> {
    vec![
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 0,
            width: 38,
            height: 420,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_0".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 0,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_1".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 15,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_2".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 30,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_3".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 45,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_4".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 60,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_5".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 75,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_6".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 90,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_7".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 105,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_8".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 120,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_9".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 135,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_10".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 150,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_11".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 165,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_12".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 180,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_13".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 195,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_14".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 210,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_15".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 225,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_16".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 240,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_17".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 255,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_18".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 270,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_19".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 285,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_20".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 300,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_21".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 315,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_22".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 330,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_23".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 345,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_24".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 360,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_25".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 375,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_26".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 390,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_BACKGROUND_27".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 9,
            y: 405,
            width: 38,
            height: 13,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_THUMB".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 15,
            y: 422,
            width: 14,
            height: 11,
        },
        SpriteDefinition {
            name: "MAIN_BALANCE_THUMB_SELECTED".to_string(),
            sprite_sheet: "BALANCE.BMP".to_string(),
            x: 0,
            y: 422,
            width: 14,
            height: 11,
        },
    ]
}

pub fn balance_window_sprites() -> Vec<SpriteWindowDefinition> {
    vec![
        SpriteWindowDefinition {
            name: "MAIN_BALANCE_BACKGROUND".to_string(),
            sprite_name: "MAIN_BALANCE_BACKGROUND_0".to_string(),
            window_type: WindowType::Main,
            layer: 1,
            x: 177,
            y: 57,
            width: 38,
            height: 13,
        },
        SpriteWindowDefinition {
            name: "MAIN_BALANCE_THUMB".to_string(),
            sprite_name: "MAIN_BALANCE_THUMB".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 189,
            y: 58,
            width: 14,
            height: 11,
        },
    ]
}
