use super::{SpriteDefinition, SpriteWindowDefinition, WindowType};

pub fn cbuttons_sprites() -> Vec<SpriteDefinition> {
    vec![
        SpriteDefinition {
            name: "MAIN_PREVIOUS_BUTTON".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 0,
            y: 0,
            width: 23,
            height: 18,
        },
        SpriteDefinition {
            name: "MAIN_PREVIOUS_BUTTON_SELECTED".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 0,
            y: 18,
            width: 23,
            height: 18,
        },
        SpriteDefinition {
            name: "MAIN_PLAY_BUTTON".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 23,
            y: 0,
            width: 23,
            height: 18,
        },
        SpriteDefinition {
            name: "MAIN_PLAY_BUTTON_SELECTED".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 23,
            y: 18,
            width: 23,
            height: 18,
        },
        SpriteDefinition {
            name: "MAIN_PAUSE_BUTTON".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 46,
            y: 0,
            width: 23,
            height: 18,
        },
        SpriteDefinition {
            name: "MAIN_PAUSE_BUTTON_SELECTED".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 46,
            y: 18,
            width: 23,
            height: 18,
        },
        SpriteDefinition {
            name: "MAIN_STOP_BUTTON".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 69,
            y: 0,
            width: 23,
            height: 18,
        },
        SpriteDefinition {
            name: "MAIN_STOP_BUTTON_SELECTED".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 69,
            y: 18,
            width: 23,
            height: 18,
        },
        SpriteDefinition {
            name: "MAIN_NEXT_BUTTON".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 92,
            y: 0,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "MAIN_NEXT_BUTTON_SELECTED".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 92,
            y: 18,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "MAIN_EJECT_BUTTON".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 114,
            y: 0,
            width: 22,
            height: 16,
        },
        SpriteDefinition {
            name: "MAIN_EJECT_BUTTON_SELECTED".to_string(),
            sprite_sheet: "CBUTTONS.BMP".to_string(),
            x: 114,
            y: 16,
            width: 22,
            height: 16,
        },
    ]
}

pub fn cbuttons_window_sprites() -> Vec<SpriteWindowDefinition> {
    vec![
        SpriteWindowDefinition {
            name: "MAIN_PREVIOUS_BUTTON".to_string(),
            sprite_name: "MAIN_PREVIOUS_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 16,
            y: 88,
            width: 23,
            height: 18,
        },
        SpriteWindowDefinition {
            name: "MAIN_PLAY_BUTTON".to_string(),
            sprite_name: "MAIN_PLAY_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 39,
            y: 88,
            width: 23,
            height: 18,
        },
        SpriteWindowDefinition {
            name: "MAIN_PAUSE_BUTTON".to_string(),
            sprite_name: "MAIN_PAUSE_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 62,
            y: 88,
            width: 23,
            height: 18,
        },
        SpriteWindowDefinition {
            name: "MAIN_STOP_BUTTON".to_string(),
            sprite_name: "MAIN_STOP_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 85,
            y: 88,
            width: 23,
            height: 18,
        },
        SpriteWindowDefinition {
            name: "MAIN_NEXT_BUTTON".to_string(),
            sprite_name: "MAIN_NEXT_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 108,
            y: 88,
            width: 22,
            height: 18,
        },
        SpriteWindowDefinition {
            name: "MAIN_EJECT_BUTTON".to_string(),
            sprite_name: "MAIN_EJECT_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 136,
            y: 89,
            width: 22,
            height: 16,
        },
    ]
}
