use super::SpriteDefinition;

pub fn eq_ex_sprites() -> Vec<SpriteDefinition> {
    vec![
        SpriteDefinition {
            name: "EQ_SHADE_BACKGROUND_SELECTED".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 0,
            y: 0,
            width: 275,
            height: 14,
        },
        SpriteDefinition {
            name: "EQ_SHADE_BACKGROUND".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 0,
            y: 15,
            width: 275,
            height: 14,
        },
        SpriteDefinition {
            name: "EQ_SHADE_VOLUME_SLIDER_LEFT".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 1,
            y: 30,
            width: 3,
            height: 7,
        },
        SpriteDefinition {
            name: "EQ_SHADE_VOLUME_SLIDER_CENTER".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 4,
            y: 30,
            width: 3,
            height: 7,
        },
        SpriteDefinition {
            name: "EQ_SHADE_VOLUME_SLIDER_RIGHT".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 7,
            y: 30,
            width: 3,
            height: 7,
        },
        SpriteDefinition {
            name: "EQ_SHADE_BALANCE_SLIDER_LEFT".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 11,
            y: 30,
            width: 3,
            height: 7,
        },
        SpriteDefinition {
            name: "EQ_SHADE_BALANCE_SLIDER_CENTER".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 14,
            y: 30,
            width: 3,
            height: 7,
        },
        SpriteDefinition {
            name: "EQ_SHADE_BALANCE_SLIDER_RIGHT".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 17,
            y: 30,
            width: 3,
            height: 7,
        },
        SpriteDefinition {
            name: "EQ_MAXIMIZE_BUTTON_ACTIVE".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 1,
            y: 38,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "EQ_MINIMIZE_BUTTON_ACTIVE".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 1,
            y: 47,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "EQ_SHADE_CLOSE_BUTTON".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 11,
            y: 38,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "EQ_SHADE_CLOSE_BUTTON_ACTIVE".to_string(),
            sprite_sheet: "EQ_EX.BMP".to_string(),
            x: 11,
            y: 47,
            width: 9,
            height: 9,
        },
    ]
}
