use super::{SpriteDefinition, SpriteWindowDefinition, WindowType};

pub fn eqmain_sprites() -> Vec<SpriteDefinition> {
    vec![
        SpriteDefinition {
            name: "EQ_WINDOW_BACKGROUND".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 0,
            y: 0,
            width: 275,
            height: 116,
        },
        SpriteDefinition {
            name: "EQ_TITLE_BAR".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 0,
            y: 149,
            width: 275,
            height: 14,
        },
        SpriteDefinition {
            name: "EQ_TITLE_BAR_SELECTED".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 0,
            y: 134,
            width: 275,
            height: 14,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 13,
            y: 164,
            width: 209,
            height: 129,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_0".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 13,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_1".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 28,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_2".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 43,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_3".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 58,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_4".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 73,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_5".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 88,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_6".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 103,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_7".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 118,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_8".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 133,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_9".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 148,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_10".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 163,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_11".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 178,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_12".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 193,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_13".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 208,
            y: 164,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 13,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_15".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 28,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_16".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 43,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_17".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 58,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_18".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 73,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_19".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 88,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_20".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 103,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_21".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 118,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_22".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 133,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_23".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 148,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_24".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 163,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_25".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 178,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_26".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 193,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_BACKGROUND_27".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 208,
            y: 229,
            width: 14,
            height: 63,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_THUMB".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 0,
            y: 164,
            width: 11,
            height: 11,
        },
        SpriteDefinition {
            name: "EQ_SLIDER_THUMB_SELECTED".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 0,
            y: 176,
            width: 11,
            height: 11,
        },
        SpriteDefinition {
            name: "EQ_CLOSE_BUTTON".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 0,
            y: 116,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "EQ_CLOSE_BUTTON_SELECTED".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 0,
            y: 125,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "EQ_MAXIMIZE_BUTTON_SELECTED_FALLBACK".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 254,
            y: 152,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "EQ_ON_BUTTON".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 10,
            y: 119,
            width: 26,
            height: 12,
        },
        SpriteDefinition {
            name: "EQ_ON_BUTTON_SELECTED".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 128,
            y: 119,
            width: 26,
            height: 12,
        },
        SpriteDefinition {
            name: "EQ_ON_BUTTON_ACTIVE".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 69,
            y: 119,
            width: 26,
            height: 12,
        },
        SpriteDefinition {
            name: "EQ_ON_BUTTON_ACTIVE_SELECTED".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 187,
            y: 119,
            width: 26,
            height: 12,
        },
        SpriteDefinition {
            name: "EQ_AUTO_BUTTON".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 36,
            y: 119,
            width: 32,
            height: 12,
        },
        SpriteDefinition {
            name: "EQ_AUTO_BUTTON_SELECTED".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 154,
            y: 119,
            width: 32,
            height: 12,
        },
        SpriteDefinition {
            name: "EQ_AUTO_BUTTON_ACTIVE".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 95,
            y: 119,
            width: 32,
            height: 12,
        },
        SpriteDefinition {
            name: "EQ_AUTO_BUTTON_ACTIVE_SELECTED".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 213,
            y: 119,
            width: 32,
            height: 12,
        },
        SpriteDefinition {
            name: "EQ_GRAPH_BACKGROUND".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 0,
            y: 294,
            width: 113,
            height: 19,
        },
        SpriteDefinition {
            name: "EQ_GRAPH_LINE_COLORS".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 115,
            y: 294,
            width: 1,
            height: 19,
        },
        SpriteDefinition {
            name: "EQ_PRESETS_BUTTON".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 224,
            y: 164,
            width: 44,
            height: 12,
        },
        SpriteDefinition {
            name: "EQ_PRESETS_BUTTON_SELECTED".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 224,
            y: 176,
            width: 44,
            height: 12,
        },
        SpriteDefinition {
            name: "EQ_PREAMP_LINE".to_string(),
            sprite_sheet: "EQMAIN.BMP".to_string(),
            x: 0,
            y: 314,
            width: 113,
            height: 1,
        },
    ]
}

pub fn eqmain_window_sprites() -> Vec<SpriteWindowDefinition> {
    vec![
        SpriteWindowDefinition {
            name: "EQ_WINDOW_BACKGROUND".to_string(),
            sprite_name: "EQ_WINDOW_BACKGROUND".to_string(),
            window_type: WindowType::Equalizer,
            layer: 0,
            x: 0,
            y: 0,
            width: 275,
            height: 116,
        },
        SpriteWindowDefinition {
            name: "EQ_TITLE_BAR".to_string(),
            sprite_name: "EQ_TITLE_BAR".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 0,
            y: 0,
            width: 275,
            height: 14,
        },
        SpriteWindowDefinition {
            name: "EQ_ON_BUTTON".to_string(),
            sprite_name: "EQ_ON_BUTTON_ACTIVE".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 14,
            y: 18,
            width: 26,
            height: 12,
        },
        SpriteWindowDefinition {
            name: "EQ_AUTO_BUTTON".to_string(),
            sprite_name: "EQ_AUTO_BUTTON".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 40,
            y: 18,
            width: 32,
            height: 12,
        },
        SpriteWindowDefinition {
            name: "EQ_PRESETS_BUTTON".to_string(),
            sprite_name: "EQ_PRESETS_BUTTON".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 217,
            y: 18,
            width: 44,
            height: 12,
        },
        SpriteWindowDefinition {
            name: "EQ_PREAMP_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 21,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_PREAMP_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 22,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_60_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 78,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_60_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 79,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_170_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 96,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_170_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 97,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_310_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 114,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_310_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 115,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_600_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 132,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_600_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 133,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_1000_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 150,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_1000_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 151,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_3000_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 168,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_3000_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 169,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_6000_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 186,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_6000_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 187,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_12000_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 204,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_12000_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 205,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_14000_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 222,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_14000_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 223,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_16000_SLIDER_BACKGROUND".to_string(),
            sprite_name: "EQ_SLIDER_BACKGROUND_14".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 240,
            y: 38,
            width: 14,
            height: 63,
        },
        SpriteWindowDefinition {
            name: "EQ_BAND_16000_SLIDER_THUMB".to_string(),
            sprite_name: "EQ_SLIDER_THUMB".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 241,
            y: 63,
            width: 11,
            height: 11,
        },
        SpriteWindowDefinition {
            name: "EQ_GRAPH_BACKGROUND".to_string(),
            sprite_name: "EQ_GRAPH_BACKGROUND".to_string(),
            window_type: WindowType::Equalizer,
            layer: 1,
            x: 86,
            y: 17,
            width: 113,
            height: 19,
        },
        SpriteWindowDefinition {
            name: "EQ_GRAPH_PREAMP_LINE".to_string(),
            sprite_name: "EQ_PREAMP_LINE".to_string(),
            window_type: WindowType::Equalizer,
            layer: 2,
            x: 86,
            y: 26,
            width: 113,
            height: 1,
        },
    ]
}
