use super::SpriteDefinition;

pub fn gen_sprites() -> Vec<SpriteDefinition> {
    vec![
        SpriteDefinition {
            name: "GEN_TOP_LEFT_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 0,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_LEFT_END_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 26,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_CENTER_FILL_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 52,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_RIGHT_END_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 78,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_LEFT_RIGHT_FILL_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 104,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_RIGHT_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 130,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_LEFT".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 0,
            y: 21,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_LEFT_END".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 26,
            y: 21,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_CENTER_FILL".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 52,
            y: 21,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_RIGHT_END".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 78,
            y: 21,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_LEFT_RIGHT_FILL".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 104,
            y: 21,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_TOP_RIGHT".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 130,
            y: 21,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "GEN_BOTTOM_LEFT".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 0,
            y: 42,
            width: 125,
            height: 14,
        },
        SpriteDefinition {
            name: "GEN_BOTTOM_RIGHT".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 0,
            y: 57,
            width: 125,
            height: 14,
        },
        SpriteDefinition {
            name: "GEN_BOTTOM_FILL".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 127,
            y: 72,
            width: 25,
            height: 14,
        },
        SpriteDefinition {
            name: "GEN_MIDDLE_LEFT".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 127,
            y: 42,
            width: 11,
            height: 29,
        },
        SpriteDefinition {
            name: "GEN_MIDDLE_LEFT_BOTTOM".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 158,
            y: 42,
            width: 11,
            height: 24,
        },
        SpriteDefinition {
            name: "GEN_MIDDLE_RIGHT".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 139,
            y: 42,
            width: 8,
            height: 29,
        },
        SpriteDefinition {
            name: "GEN_MIDDLE_RIGHT_BOTTOM".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 170,
            y: 42,
            width: 8,
            height: 24,
        },
        SpriteDefinition {
            name: "GEN_CLOSE_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 148,
            y: 42,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "GEN_CHAR_A_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 1,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_B_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 8,
            y: 88,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_C_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 16,
            y: 88,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_D_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 24,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_E_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 31,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_F_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 38,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_G_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 45,
            y: 88,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_H_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 53,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_I_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 60,
            y: 88,
            width: 4,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_J_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 65,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_K_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 73,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_L_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 80,
            y: 88,
            width: 5,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_M_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 86,
            y: 88,
            width: 8,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_N_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 95,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_O_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 102,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_P_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 109,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_Q_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 116,
            y: 88,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_R_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 124,
            y: 88,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_S_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 132,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_T_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 139,
            y: 88,
            width: 5,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_U_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 145,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_V_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 152,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_W_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 159,
            y: 88,
            width: 8,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_X_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 168,
            y: 88,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_Y_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 176,
            y: 88,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_Z_SELECTED".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 183,
            y: 88,
            width: 5,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_A".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 1,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_B".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 8,
            y: 96,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_C".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 16,
            y: 96,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_D".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 24,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_E".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 31,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_F".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 38,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_G".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 45,
            y: 96,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_H".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 53,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_I".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 60,
            y: 96,
            width: 4,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_J".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 65,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_K".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 73,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_L".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 80,
            y: 96,
            width: 5,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_M".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 86,
            y: 96,
            width: 8,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_N".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 95,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_O".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 102,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_P".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 109,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_Q".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 116,
            y: 96,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_R".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 124,
            y: 96,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_S".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 132,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_T".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 139,
            y: 96,
            width: 5,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_U".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 145,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_V".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 152,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_W".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 159,
            y: 96,
            width: 8,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_X".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 168,
            y: 96,
            width: 7,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_Y".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 176,
            y: 96,
            width: 6,
            height: 7,
        },
        SpriteDefinition {
            name: "GEN_CHAR_Z".to_string(),
            sprite_sheet: "GEN.BMP".to_string(),
            x: 183,
            y: 96,
            width: 5,
            height: 7,
        },
    ]
}
