use super::SpriteDefinition;

pub fn numbers_sprites() -> Vec<SpriteDefinition> {
    vec![
        SpriteDefinition {
            name: "NO_MINUS_SIGN".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 9,
            y: 6,
            width: 5,
            height: 1,
        },
        SpriteDefinition {
            name: "MINUS_SIGN".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 20,
            y: 6,
            width: 5,
            height: 1,
        },
        SpriteDefinition {
            name: "DIGIT_0".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 0,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_1".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 9,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_2".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 18,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_3".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 27,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_4".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 36,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_5".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 45,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_6".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 54,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_7".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 63,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_8".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 72,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_9".to_string(),
            sprite_sheet: "NUMBERS.BMP".to_string(),
            x: 81,
            y: 0,
            width: 9,
            height: 13,
        },
    ]
}
