use super::SpriteDefinition;

pub fn nums_ex_sprites() -> Vec<SpriteDefinition> {
    vec![
        SpriteDefinition {
            name: "NO_MINUS_SIGN_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 90,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "MINUS_SIGN_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 99,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_0_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 0,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_1_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 9,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_2_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 18,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_3_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 27,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_4_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 36,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_5_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 45,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_6_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 54,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_7_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 63,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_8_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 72,
            y: 0,
            width: 9,
            height: 13,
        },
        SpriteDefinition {
            name: "DIGIT_9_EX".to_string(),
            sprite_sheet: "NUMS_EX.BMP".to_string(),
            x: 81,
            y: 0,
            width: 9,
            height: 13,
        },
    ]
}
