use super::{SpriteDefinition, SpriteWindowDefinition, WindowType};

pub fn pledit_sprites() -> Vec<SpriteDefinition> {
    vec![
        SpriteDefinition {
            name: "PLAYLIST_TOP_TILE".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 127,
            y: 21,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "PLAYLIST_TOP_LEFT_CORNER".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 0,
            y: 21,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "PLAYLIST_TITLE_BAR".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 26,
            y: 21,
            width: 100,
            height: 20,
        },
        SpriteDefinition {
            name: "PLAYLIST_TOP_RIGHT_CORNER".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 153,
            y: 21,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "PLAYLIST_TOP_TILE_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 127,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "PLAYLIST_TOP_LEFT_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 0,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "PLAYLIST_TITLE_BAR_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 26,
            y: 0,
            width: 100,
            height: 20,
        },
        SpriteDefinition {
            name: "PLAYLIST_TOP_RIGHT_CORNER_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 153,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteDefinition {
            name: "PLAYLIST_LEFT_TILE".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 0,
            y: 42,
            width: 12,
            height: 29,
        },
        SpriteDefinition {
            name: "PLAYLIST_RIGHT_TILE".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 31,
            y: 42,
            width: 20,
            height: 29,
        },
        SpriteDefinition {
            name: "PLAYLIST_BOTTOM_TILE".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 179,
            y: 0,
            width: 25,
            height: 38,
        },
        SpriteDefinition {
            name: "PLAYLIST_BOTTOM_LEFT_CORNER".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 0,
            y: 72,
            width: 125,
            height: 38,
        },
        SpriteDefinition {
            name: "PLAYLIST_BOTTOM_RIGHT_CORNER".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 126,
            y: 72,
            width: 150,
            height: 38,
        },
        SpriteDefinition {
            name: "PLAYLIST_VISUALIZER_BACKGROUND".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 205,
            y: 0,
            width: 75,
            height: 38,
        },
        SpriteDefinition {
            name: "PLAYLIST_SHADE_BACKGROUND".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 72,
            y: 57,
            width: 25,
            height: 14,
        },
        SpriteDefinition {
            name: "PLAYLIST_SHADE_BACKGROUND_LEFT".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 72,
            y: 42,
            width: 25,
            height: 14,
        },
        SpriteDefinition {
            name: "PLAYLIST_SHADE_BACKGROUND_RIGHT".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 99,
            y: 57,
            width: 50,
            height: 14,
        },
        SpriteDefinition {
            name: "PLAYLIST_SHADE_BACKGROUND_RIGHT_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 99,
            y: 42,
            width: 50,
            height: 14,
        },
        SpriteDefinition {
            name: "PLAYLIST_SCROLL_HANDLE_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 61,
            y: 53,
            width: 8,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_SCROLL_HANDLE".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 52,
            y: 53,
            width: 8,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_ADD_URL".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 0,
            y: 111,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_ADD_URL_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 23,
            y: 111,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_ADD_DIR".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 0,
            y: 130,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_ADD_DIR_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 23,
            y: 130,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_ADD_FILE".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 0,
            y: 149,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_ADD_FILE_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 23,
            y: 149,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_REMOVE_ALL".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 54,
            y: 111,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_REMOVE_ALL_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 77,
            y: 111,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_CROP".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 54,
            y: 130,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_CROP_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 77,
            y: 130,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_REMOVE_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 54,
            y: 149,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_REMOVE_SELECTED_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 77,
            y: 149,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_REMOVE_MISC".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 54,
            y: 168,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_REMOVE_MISC_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 77,
            y: 168,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_INVERT_SELECTION".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 104,
            y: 111,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_INVERT_SELECTION_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 127,
            y: 111,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_SELECT_ZERO".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 104,
            y: 130,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_SELECT_ZERO_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 127,
            y: 130,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_SELECT_ALL".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 104,
            y: 149,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_SELECT_ALL_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 127,
            y: 149,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_SORT_LIST".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 154,
            y: 111,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_SORT_LIST_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 177,
            y: 111,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_FILE_INFO".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 154,
            y: 130,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_FILE_INFO_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 177,
            y: 130,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_MISC_OPTIONS".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 154,
            y: 149,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_MISC_OPTIONS_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 177,
            y: 149,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_NEW_LIST".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 204,
            y: 111,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_NEW_LIST_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 227,
            y: 111,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_SAVE_LIST".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 204,
            y: 130,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_SAVE_LIST_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 227,
            y: 130,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_LOAD_LIST".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 204,
            y: 149,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_LOAD_LIST_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 227,
            y: 149,
            width: 22,
            height: 18,
        },
        SpriteDefinition {
            name: "PLAYLIST_ADD_MENU_BAR".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 48,
            y: 111,
            width: 3,
            height: 54,
        },
        SpriteDefinition {
            name: "PLAYLIST_REMOVE_MENU_BAR".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 100,
            y: 111,
            width: 3,
            height: 72,
        },
        SpriteDefinition {
            name: "PLAYLIST_SELECT_MENU_BAR".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 150,
            y: 111,
            width: 3,
            height: 54,
        },
        SpriteDefinition {
            name: "PLAYLIST_MISC_MENU_BAR".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 200,
            y: 111,
            width: 3,
            height: 54,
        },
        SpriteDefinition {
            name: "PLAYLIST_LIST_BAR".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 250,
            y: 111,
            width: 3,
            height: 54,
        },
        SpriteDefinition {
            name: "PLAYLIST_CLOSE_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 52,
            y: 42,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "PLAYLIST_COLLAPSE_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 62,
            y: 42,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "PLAYLIST_EXPAND_SELECTED".to_string(),
            sprite_sheet: "PLEDIT.BMP".to_string(),
            x: 150,
            y: 42,
            width: 9,
            height: 9,
        },
    ]
}

pub fn pledit_window_sprites() -> Vec<SpriteWindowDefinition> {
    vec![
        SpriteWindowDefinition {
            name: "PLAYLIST_TOP_LEFT_CORNER".to_string(),
            sprite_name: "PLAYLIST_TOP_LEFT_CORNER".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 0,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_TOP_TILE_0".to_string(),
            sprite_name: "PLAYLIST_TOP_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 25,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_TOP_TILE_1".to_string(),
            sprite_name: "PLAYLIST_TOP_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 50,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_TOP_TILE_2".to_string(),
            sprite_name: "PLAYLIST_TOP_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 75,
            y: 0,
            width: 25,
            height: 20,
        },
        // n.b. this overlaps the previous and next tiles. this is intentional.
        SpriteWindowDefinition {
            name: "PLAYLIST_TITLE_BAR".to_string(),
            sprite_name: "PLAYLIST_TITLE_BAR".to_string(),
            window_type: WindowType::Playlist,
            layer: 2,
            x: 87,
            y: 0,
            width: 100,
            height: 20,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_TOP_TILE_3".to_string(),
            sprite_name: "PLAYLIST_TOP_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 175,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_TOP_TILE_4".to_string(),
            sprite_name: "PLAYLIST_TOP_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 200,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_TOP_TILE_5".to_string(),
            sprite_name: "PLAYLIST_TOP_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 225,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_TOP_RIGHT_CORNER".to_string(),
            sprite_name: "PLAYLIST_TOP_RIGHT_CORNER".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 250,
            y: 0,
            width: 25,
            height: 20,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_LEFT_TILE_0".to_string(),
            sprite_name: "PLAYLIST_LEFT_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 0,
            y: 20,
            width: 12,
            height: 29,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_RIGHT_TILE_0".to_string(),
            sprite_name: "PLAYLIST_RIGHT_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 255,
            y: 20,
            width: 20,
            height: 29,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_SCROLL_HANDLE".to_string(),
            sprite_name: "PLAYLIST_SCROLL_HANDLE".to_string(),
            window_type: WindowType::Playlist,
            layer: 2,
            x: 260,
            y: 20,
            width: 8,
            height: 18,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_LEFT_TILE_1".to_string(),
            sprite_name: "PLAYLIST_LEFT_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 0,
            y: 49,
            width: 12,
            height: 29,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_RIGHT_TILE_1".to_string(),
            sprite_name: "PLAYLIST_RIGHT_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 255,
            y: 49,
            width: 20,
            height: 29,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_LEFT_TILE_2".to_string(),
            sprite_name: "PLAYLIST_LEFT_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 0,
            y: 78,
            width: 12,
            height: 29,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_RIGHT_TILE_2".to_string(),
            sprite_name: "PLAYLIST_RIGHT_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 255,
            y: 78,
            width: 20,
            height: 29,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_LEFT_TILE_3".to_string(),
            sprite_name: "PLAYLIST_LEFT_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 0,
            y: 107,
            width: 12,
            height: 29,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_RIGHT_TILE_3".to_string(),
            sprite_name: "PLAYLIST_RIGHT_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 255,
            y: 107,
            width: 20,
            height: 29,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_LEFT_TILE_4".to_string(),
            sprite_name: "PLAYLIST_LEFT_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 0,
            y: 136,
            width: 12,
            height: 29,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_RIGHT_TILE_4".to_string(),
            sprite_name: "PLAYLIST_RIGHT_TILE".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 255,
            y: 136,
            width: 20,
            height: 29,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_BOTTOM_LEFT_CORNER".to_string(),
            sprite_name: "PLAYLIST_BOTTOM_LEFT_CORNER".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 0,
            y: 165,
            width: 125,
            height: 38,
        },
        SpriteWindowDefinition {
            name: "PLAYLIST_BOTTOM_RIGHT_CORNER".to_string(),
            sprite_name: "PLAYLIST_BOTTOM_RIGHT_CORNER".to_string(),
            window_type: WindowType::Playlist,
            layer: 1,
            x: 125,
            y: 165,
            width: 150,
            height: 38,
        },
    ]
}
