use super::{SpriteDefinition, SpriteWindowDefinition, WindowType};

pub fn shufrep_sprites() -> Vec<SpriteDefinition> {
    vec![
        SpriteDefinition {
            name: "MAIN_SHUFFLE_BUTTON".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 28,
            y: 0,
            width: 47,
            height: 15,
        },
        SpriteDefinition {
            name: "MAIN_SHUFFLE_BUTTON_SELECTED".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 28,
            y: 15,
            width: 47,
            height: 15,
        },
        SpriteDefinition {
            name: "MAIN_SHUFFLE_BUTTON_ACTIVE".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 28,
            y: 30,
            width: 47,
            height: 15,
        },
        SpriteDefinition {
            name: "MAIN_SHUFFLE_BUTTON_ACTIVE_SELECTED".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 28,
            y: 45,
            width: 47,
            height: 15,
        },
        SpriteDefinition {
            name: "MAIN_REPEAT_BUTTON".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 0,
            y: 0,
            width: 28,
            height: 15,
        },
        SpriteDefinition {
            name: "MAIN_REPEAT_BUTTON_SELECTED".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 0,
            y: 15,
            width: 28,
            height: 15,
        },
        SpriteDefinition {
            name: "MAIN_REPEAT_BUTTON_ACTIVE".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 0,
            y: 30,
            width: 28,
            height: 15,
        },
        SpriteDefinition {
            name: "MAIN_REPEAT_BUTTON_ACTIVE_SELECTED".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 0,
            y: 45,
            width: 28,
            height: 15,
        },
        SpriteDefinition {
            name: "MAIN_EQ_BUTTON".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 0,
            y: 61,
            width: 23,
            height: 12,
        },
        SpriteDefinition {
            name: "MAIN_EQ_BUTTON_ACTIVE".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 0,
            y: 73,
            width: 23,
            height: 12,
        },
        SpriteDefinition {
            name: "MAIN_EQ_BUTTON_SELECTED".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 46,
            y: 61,
            width: 23,
            height: 12,
        },
        SpriteDefinition {
            name: "MAIN_EQ_BUTTON_ACTIVE_SELECTED".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 46,
            y: 73,
            width: 23,
            height: 12,
        },
        SpriteDefinition {
            name: "MAIN_PLAYLIST_BUTTON".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 23,
            y: 61,
            width: 23,
            height: 12,
        },
        SpriteDefinition {
            name: "MAIN_PLAYLIST_BUTTON_ACTIVE".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 23,
            y: 73,
            width: 23,
            height: 12,
        },
        SpriteDefinition {
            name: "MAIN_PLAYLIST_BUTTON_SELECTED".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 69,
            y: 61,
            width: 23,
            height: 12,
        },
        SpriteDefinition {
            name: "MAIN_PLAYLIST_BUTTON_ACTIVE_SELECTED".to_string(),
            sprite_sheet: "SHUFREP.BMP".to_string(),
            x: 69,
            y: 73,
            width: 23,
            height: 12,
        },
    ]
}

pub fn shufrep_window_sprites() -> Vec<SpriteWindowDefinition> {
    vec![
        SpriteWindowDefinition {
            name: "MAIN_SHUFFLE_BUTTON".to_string(),
            sprite_name: "MAIN_SHUFFLE_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 164,
            y: 89,
            width: 47,
            height: 15,
        },
        SpriteWindowDefinition {
            name: "MAIN_REPEAT_BUTTON".to_string(),
            sprite_name: "MAIN_REPEAT_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 210,
            y: 89,
            width: 28,
            height: 15,
        },
        SpriteWindowDefinition {
            name: "MAIN_EQ_BUTTON".to_string(),
            sprite_name: "MAIN_EQ_BUTTON_ACTIVE".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 219,
            y: 58,
            width: 23,
            height: 12,
        },
        SpriteWindowDefinition {
            name: "MAIN_PLAYLIST_BUTTON".to_string(),
            sprite_name: "MAIN_PLAYLIST_BUTTON_ACTIVE".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 242,
            y: 58,
            width: 23,
            height: 12,
        },
    ]
}
