use super::{SpriteDefinition, SpriteWindowDefinition, WindowType};

pub fn titlebar_sprites() -> Vec<SpriteDefinition> {
    vec![
        SpriteDefinition {
            name: "MAIN_TITLE_BAR".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 27,
            y: 15,
            width: 275,
            height: 14,
        },
        SpriteDefinition {
            name: "MAIN_TITLE_BAR_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 27,
            y: 0,
            width: 275,
            height: 14,
        },
        SpriteDefinition {
            name: "MAIN_EASTER_EGG_TITLE_BAR".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 27,
            y: 72,
            width: 275,
            height: 14,
        },
        SpriteDefinition {
            name: "MAIN_EASTER_EGG_TITLE_BAR_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 27,
            y: 57,
            width: 275,
            height: 14,
        },
        SpriteDefinition {
            name: "MAIN_OPTIONS_BUTTON".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 0,
            y: 0,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "MAIN_OPTIONS_BUTTON_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 0,
            y: 9,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "MAIN_MINIMIZE_BUTTON".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 9,
            y: 0,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "MAIN_MINIMIZE_BUTTON_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 9,
            y: 9,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "MAIN_SHADE_BUTTON".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 0,
            y: 18,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "MAIN_SHADE_BUTTON_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 9,
            y: 18,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "MAIN_CLOSE_BUTTON".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 18,
            y: 0,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "MAIN_CLOSE_BUTTON_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 18,
            y: 9,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "MAIN_CLUTTER_BAR_BACKGROUND".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 304,
            y: 0,
            width: 8,
            height: 43,
        },
        SpriteDefinition {
            name: "MAIN_CLUTTER_BAR_BACKGROUND_DISABLED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 312,
            y: 0,
            width: 8,
            height: 43,
        },
        SpriteDefinition {
            name: "MAIN_CLUTTER_BAR_BUTTON_O_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 304,
            y: 47,
            width: 8,
            height: 8,
        },
        SpriteDefinition {
            name: "MAIN_CLUTTER_BAR_BUTTON_A_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 312,
            y: 55,
            width: 8,
            height: 7,
        },
        SpriteDefinition {
            name: "MAIN_CLUTTER_BAR_BUTTON_I_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 320,
            y: 62,
            width: 8,
            height: 7,
        },
        SpriteDefinition {
            name: "MAIN_CLUTTER_BAR_BUTTON_D_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 328,
            y: 69,
            width: 8,
            height: 8,
        },
        SpriteDefinition {
            name: "MAIN_CLUTTER_BAR_BUTTON_V_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 336,
            y: 77,
            width: 8,
            height: 7,
        },
        SpriteDefinition {
            name: "MAIN_SHADE_BACKGROUND".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 27,
            y: 42,
            width: 275,
            height: 14,
        },
        SpriteDefinition {
            name: "MAIN_SHADE_BACKGROUND_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 27,
            y: 29,
            width: 275,
            height: 14,
        },
        SpriteDefinition {
            name: "MAIN_SHADE_BUTTON_ACTIVE".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 0,
            y: 27,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "MAIN_SHADE_BUTTON_ACTIVE_SELECTED".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 9,
            y: 27,
            width: 9,
            height: 9,
        },
        SpriteDefinition {
            name: "MAIN_SHADE_POSITION_BACKGROUND".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 0,
            y: 36,
            width: 17,
            height: 7,
        },
        SpriteDefinition {
            name: "MAIN_SHADE_POSITION_THUMB".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 20,
            y: 36,
            width: 3,
            height: 7,
        },
        SpriteDefinition {
            name: "MAIN_SHADE_POSITION_THUMB_LEFT".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 17,
            y: 36,
            width: 3,
            height: 7,
        },
        SpriteDefinition {
            name: "MAIN_SHADE_POSITION_THUMB_RIGHT".to_string(),
            sprite_sheet: "TITLEBAR.BMP".to_string(),
            x: 23,
            y: 36,
            width: 3,
            height: 7,
        },
    ]
}

pub fn titlebar_window_sprites() -> Vec<SpriteWindowDefinition> {
    vec![
        SpriteWindowDefinition {
            name: "MAIN_TITLE_BAR".to_string(),
            sprite_name: "MAIN_TITLE_BAR_SELECTED".to_string(),
            window_type: WindowType::Main,
            layer: 1,
            x: 0,
            y: 0,
            width: 275,
            height: 14,
        },
        SpriteWindowDefinition {
            name: "MAIN_OPTIONS_BUTTON".to_string(),
            sprite_name: "MAIN_OPTIONS_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 6,
            y: 3,
            width: 9,
            height: 9,
        },
        SpriteWindowDefinition {
            name: "MAIN_MINIMIZE_BUTTON".to_string(),
            sprite_name: "MAIN_MINIMIZE_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 244,
            y: 3,
            width: 9,
            height: 9,
        },
        SpriteWindowDefinition {
            name: "MAIN_SHADE_BUTTON".to_string(),
            sprite_name: "MAIN_SHADE_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 254,
            y: 3,
            width: 9,
            height: 9,
        },
        SpriteWindowDefinition {
            name: "MAIN_CLOSE_BUTTON".to_string(),
            sprite_name: "MAIN_CLOSE_BUTTON".to_string(),
            window_type: WindowType::Main,
            layer: 2,
            x: 264,
            y: 3,
            width: 9,
            height: 9,
        },
        SpriteWindowDefinition {
            name: "MAIN_CLUTTER_BAR_BACKGROUND".to_string(),
            sprite_name: "MAIN_CLUTTER_BAR_BACKGROUND".to_string(),
            window_type: WindowType::Main,
            layer: 1,
            x: 10,
            y: 22,
            width: 8,
            height: 43,
        },
    ]
}
